---
title: "Exploratory Data Analysis"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library("tidyverse")
library("dplyr")
library('fpp2')
library('tseries')
library("zoo")
```

```{r}
source("functions/globals.R")
```

```{r}
#load the data
construction <- read.csv("../data/VIP-mf.csv")
date_index <- read.csv("../data/date-index.csv")

#create time series and plot for overall spending
overall_spending_ts <- filter_data_ts(1, 1)

ma.trailing <- rollmean(overall_spending_ts, k = 12, align = "right")
ma.centered <- ma(overall_spending_ts, order = 12)
plot(overall_spending_ts, xlab = "Year", ylab = "Overall Total Spending", bty = "l")
lines(ma.trailing, lwd = 2, lty = 2)
lines(ma.centered, lwd = 2)

```
```{r}
#decompose total construction spending
overall_spending_stl = stl(overall_spending_ts, s.window = 'periodic')
autoplot(overall_spending_stl, main = 'Trend and Seasonal Decomposition of Total Construction Spending')
```

```{r}
#create time series and plot for commercial-private spending
private_commercial_ts <- filter_data_ts(6, 2)

ma.trailing <- rollmean(private_commercial_ts, k = 12, align = "right")
ma.centered <- ma(private_commercial_ts, order = 12)
plot(private_commercial_ts, xlab = "Year", ylab = "Total Private-Commercial Spending", bty = "l")
lines(ma.trailing, lwd = 2, lty = 2)
lines(ma.centered, lwd = 2)
```
```{r}
#decompose commercial-private spending
private_commercial_stl = stl(private_commercial_ts, s.window = 'periodic')
autoplot(private_commercial_stl, main = 'Trend and Seasonal Decomposition of Commercial-Private Spending')
```

```{r}
#create time series and plot for total plublic spending
public_total_ts <- filter_data_ts(1, 3)

ma.trailing <- rollmean(public_total_ts, k = 12, align = "right")
ma.centered <- ma(public_total_ts, order = 12)
plot(public_total_ts, xlab = "Year", ylab = "Total Public Spending", bty = "l")
lines(ma.trailing, lwd = 2, lty = 2)
lines(ma.centered, lwd = 2)
```
```{r}
#decompose public total spending
public_total_stl = stl(public_total_ts, s.window = 'periodic')
autoplot(public_total_stl, main = 'Trend and Seasonal Decomposition of Public Total Spending')
```


```{r}
#create time series and plot for total private spending
private_total_ts <- filter_data_ts(1, 2)

ma.trailing <- rollmean(private_total_ts, k = 12, align = "right")
ma.centered <- ma(private_total_ts, order = 12)
plot(private_total_ts, xlab = "Year", ylab = "Total Private Spending", bty = "l")
lines(ma.trailing, lwd = 2, lty = 2)
lines(ma.centered, lwd = 2)
```
```{r}
#decompose total private spending
private_total_stl = stl(private_total_ts, s.window = 'periodic')
autoplot(private_total_stl, main = 'Trend and Seasonal Decomposition of Private Total Spending')
```


```{r}
#create time series and plot for total residential spending
residential_total <- filter_data_ts(2,1)

ma.trailing <- rollmean(residential_total, k = 12, align = "right")
ma.centered <- ma(residential_total, order = 12)
plot(residential_total, xlab = "Year", ylab = "Total Residential Spending", bty = "l")
lines(ma.trailing, lwd = 2, lty = 2)
lines(ma.centered, lwd = 2)
```
```{r}
#decompose total residential spending
residential_total_stl = stl(residential_total, s.window = 'periodic')
autoplot(residential_total_stl, main = 'Trend and Seasonal Decomposition of Total Residential Spending')
```


```{r}
#autoplot(filter_data_ts(1, 3))
adf.test(filter_data_ts(5, 3))
autoplot(diff(overall_spending_ts))
```

# Testing via Augmented Dickey-Fuller Test
```{r}
# nonstationary: bad stationary: good
# https://www.investopedia.com/articles/trading/07/stationary.asp
adf.test(overall_spending_ts)
adf.test(diff(overall_spending_ts))
adf.test(private_commercial_ts)
adf.test(public_total_ts)
adf.test(private_total_ts)

```

```{r}
#autocorrelation plot for overall spending
acf(overall_spending_ts, lag.max = 40)
```
```{r}
#autocorrelation plot for total public spending
acf(public_total_ts, lag.max = 40)
```

```{r}
#autocorrelation plot for total private spending
acf(private_total_ts, lag.max = 40)
```


```{r}
ar1_close <- Arima(overall_spending_ts, order = c(1,0,0))
ar1_diff <- Arima(diff(overall_spending_ts), order = c(1,0,0))

print(ar1_close)
print(ar1_diff)
```
Preprocessing

```{r}
#remove trend and seasonality from total spending:
overall.diff.twice <- diff(diff(overall_spending_ts, lag = 12), lag = 1)
plot(overall.diff.twice)
```

```{r}
#remove trend and seasonality from total public spending:
public.diff.twice <- diff(diff(public_total_ts, lag = 12), lag = 1)
plot(public.diff.twice)
```
```{r}
#remove trend and seasonality from total private spending:
private.diff.twice <- diff(diff(private_total_ts, lag = 12), lag = 1)
plot(private.diff.twice)
```
