---
title: "Arima Forecasts"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
library("tidyverse")
library("dplyr")
library('fpp2')
library('tseries')
library("zoo")
library("lubridate")
```

```{r}
source("functions/globals.R")
```

```{r}
set.seed(0)
```

```{r}
#load the data
construction <- read.csv("../data/VIP-mf.csv")
date_index <- read.csv("../data/date-index.csv")
```
```{r}
#create time series for overall spending
overall_spendingTS <- filter_data_ts(1, 1)

# Training Period set from Jan 2002 to Jun 2022
# Validation covers following three months July, August, September
train_spending <- window(overall_spendingTS, start=c(2002,1), end=c(2022,6))
validation_spending <- window(overall_spendingTS, start=c(2022,7))
```

```{r}
# looking at overall acf
acf(overall_spendingTS, lag.max = 50)

# looking at a single difference
acf(diff(overall_spendingTS), lag.max = 50)

pacf(diff(overall_spendingTS), lag.max = 50)
```

```{r}
# looking at seasonal differences
pacf(diff(diff(overall_spendingTS)), lag.max = 50)
acf(diff(diff(overall_spendingTS)), lag.max = 50)
```

```{r}
auto_model <- auto.arima(train_spending)
auto_model
```
```{r}
auto_model_cv <- function(x, h){forecast(auto.arima(x),  h=h)}
auto_model_errors <- tsCV(overall_spendingTS,
                          auto_model_cv,
                          h=1,
                          window = 60)

#mean error
mean(auto_model_errors, na.rm = TRUE)
```

```{r}
#root mean square error
sqrt(mean(auto_model_errors^2, na.rm = TRUE))
```

```{r}
#mean absolute error
mean(abs(auto_model_errors), na.rm = TRUE)
```

```{r}
arima_model <- arima(train_spending, order = c(0,2,3), seasonal = c(0,1,2))
arima_model
```
```{r}
arima_model_pred <- forecast(arima_model, h = 1 )
summary(arima_model_pred)
```
```{r}
autoplot(train_spending) +
  autolayer(arima_model_pred, color = "#006d2c", series = "ARIMA") +
  autolayer(validation_spending, color = "blue", series = "Actual")
```

```{r}
arima_model_cv <- function(x, h){forecast(arima(x, order = c(0,2,3), seasonal = c(0,1,2)),  h=h)}
arima_model_errors <- tsCV(overall_spendingTS,
                          arima_model_cv,
                          h=1,
                          window = 60)

#mean error
mean(arima_model_errors, na.rm = TRUE)
```

```{r}
#root mean square error
sqrt(mean(arima_model_errors^2, na.rm = TRUE))
```

```{r}
#mean absolute error
mean(abs(arima_model_errors), na.rm = TRUE)
```
