---
title: "Linear Regression Forecasts"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
library("tidyverse")
library("dplyr")
library('fpp2')
library('tseries')
library("zoo")
library("lubridate")
```

```{r}
source("functions/globals.R")
```

```{r}
set.seed(0)
```


```{r}
#load the data
construction <- read.csv("../data/VIP-mf.csv")
date_index <- read.csv("../data/date-index.csv")
```
```{r}
#create time series for overall spending
overall_spendingTS <- filter_data_ts(1, 1)

# Training Period set from Jan 2002 to Jun 2022
# Validation covers following three months July, August, September
train_spending <- window(overall_spendingTS, start=c(2002,1), end=c(2022,6))
validation_spending <- window(overall_spendingTS, start=c(2022,7))
```

```{r}
lm_trend_season = tslm(train_spending ~ trend + season)

summary(lm_trend_season)
```

```{r}
linear_model_cv <- function(x, h){forecast(tslm(x ~ trend + season),  h=h)}
linear_model_errors <- tsCV(overall_spendingTS,
                          linear_model_cv,
                          h=1,
                          window = 60)
#mean error
mean(linear_model_errors, na.rm = TRUE)
```
```{r}
#root mean square error
sqrt(mean(linear_model_errors^2, na.rm = TRUE))
```

```{r}
#mean absolute error
mean(abs(linear_model_errors), na.rm = TRUE)
```


