---
title: "Naive Forecasts"
output: html_document
---
```{r}
library("tidyverse")
library("dplyr")
library('fpp2')
library('tseries')
library("zoo")
library("lubridate")
```

```{r}

source("functions/globals.R")

```

```{r}
#load the data
construction <- read.csv("../data/VIP-mf.csv")
date_index <- read.csv("../data/date-index.csv")
```
```{r}
#create time series for overall spending
overall_spendingTS <- filter_data_ts(1, 1)

# Training Period set from Jan 2002 to Jun 2022
# Validation covers following three months July, August, September
train_spending <- window(overall_spendingTS, start=c(2002,1), end=c(2022,6))
validation_spending <- window(overall_spendingTS, start=c(2022,7))
```

# Naive Model
```{r}
# naive model
n_model <- naive(train_spending, h = 1)
summary(n_model)
```

```{r}
autoplot(train_spending) +
  autolayer(n_model, color = "#006d2c", series = "Naive") +
  autolayer(validation_spending, color = "blue", series = "Actual")
```
```{r}
naive_cv <- function(x, h){forecast(naive(x, h=h))}
naive_errors <- tsCV(overall_spendingTS,
                     naive_cv,
                     h=1,
                     window = 60)

mean(abs(naive_errors), na.rm = TRUE)
```
```{r}
sd(naive_errors, na.rm = TRUE)
```

# Seasonal Naive Model
```{r}
# Seasonal Naive Model
sn_model <- snaive(train_spending, h = 1)

summary(sn_model)
```

```{r}
autoplot(train_spending) +
  autolayer(sn_model, color = "#006d2c", series = "Seasonal Naive") +
  autolayer(validation_spending, color = "blue", series = "Actual")
```


```{r}
snaive_cv <- function(x, h){forecast(snaive(x, h=h))}
snaive_errors <- tsCV(overall_spendingTS,
                     snaive_cv,
                     h=1,
                     window = 60)

mean(abs(snaive_errors), na.rm = TRUE)
```
```{r}
sd(snaive_errors, na.rm = TRUE)
```

